/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Club.Health.Doctor;

//import UserInterface.Club.Finance.Accountant.*;
import Test.Feng.TestMainJFrame;
import TheSystem.Common.Person.Person;
import TheClub.Health.Doctor.Doctor;
import TheClub.Team.Team;
//import java.awt.Graphics;
import java.awt.Color;
import java.awt.Image;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Jiafeng
 */
public class DoctorJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountantJFrame
     */
    Doctor doctor;
    
    public DoctorJFrame(Person personTemp) {
        initComponents();
        Team team = new Team(personTemp); //初始化Team对象 里面含有全部的医生 Initialize the Team object containing all the Doctors
        
        int length = team.getDoctorCatalog().getDoctorCata().size();//计算catalog中有多少个医生 Calculate how many Doctors are in the catalog
        for(int i =0; i<length ; i++){
            Doctor doctorTemp = team.getDoctorCatalog().getDoctorCata().get(i);
            if(doctorTemp.getUsername().equals(personTemp.getUsername())){
                this.doctor=doctorTemp; 
                //找到在catalog中被初始化的那个doctor 和自己用户名一致的，将其对象指针传递过来
                //Find the doctor that was initialized in catalog that matches your username and pass it the object pointer
            }
        }
        
        int length2 = this.doctor.getTeam().getPlayerCatalog().getPlayerCata().size(); 
        //医生对象中的Team对象，找到队员总数 
        //Find the total number of team members in the Team object of the Doctor object
//        for(int i=0;i<length2;i++){
//        System.out.println(this.doctor.getTeam().getPlayerCatalog().getPlayerCata().get(i).getUsername());  
//        }
        nameMainLabel.setText(personTemp.getName());
        Enumeration<AbstractButton> button;
        button=doctorJFrameButtonGroup.getElements();
        AbstractButton buttonChoose; //buttonChoose = jButton1 is true
        for(int i=0;i<doctorJFrameButtonGroup.getButtonCount();i++)
        {
              buttonChoose=button.nextElement();
              buttonChoose.setBackground(new java.awt.Color(255, 255, 255));
              buttonChoose.setForeground(Color.black);
            
        }   
    }
    
//    public void imageBackground(){
//        ImageIcon oldIcon= new ImageIcon("/1234.png");
//        Image oldImage = oldIcon.getImage();
//        Image newImage= oldImage.getScaledInstance(backgroundPictureLabel.getWidth(), backgroundPictureLabel.getHeight(), Image.SCALE_AREA_AVERAGING);
//        ImageIcon newIcon = new ImageIcon(newImage);
//        backgroundPictureLabel.setIcon(newIcon);
//    }
    
    //构造器 用于初始化 Constructor Used to initialize
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorJFrameButtonGroup = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginOutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameMainLabel = new javax.swing.JLabel();
        faceToFaceDignoseButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        backgroundPictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(800, 600));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(61, 174, 72));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 600));

        loginOutButton.setText("<html>Login Out</html>");
        doctorJFrameButtonGroup.add(loginOutButton);
        loginOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginOutButton.setMaximumSize(new java.awt.Dimension(100, 23));
        loginOutButton.setMinimumSize(new java.awt.Dimension(72, 23));
        loginOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginOutButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameMainLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nameMainLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameMainLabel.setText("------------------");
        nameMainLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        faceToFaceDignoseButton.setText("<html>FaceToFace<br/>&nbsp Diagnose</html>");
        doctorJFrameButtonGroup.add(faceToFaceDignoseButton);
        faceToFaceDignoseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        faceToFaceDignoseButton.setMaximumSize(new java.awt.Dimension(90, 23));
        faceToFaceDignoseButton.setMinimumSize(new java.awt.Dimension(90, 23));
        faceToFaceDignoseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceToFaceDignoseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(faceToFaceDignoseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameMainLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(loginOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(faceToFaceDignoseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 139, 69));
        jPanel2.setMaximumSize(new java.awt.Dimension(700, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 600));

        backgroundPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TheSystem/Common/SelfDesignIcon/700_600_selfDesigned_Doctor.png"))); // NOI18N
        backgroundPictureLabel.setMaximumSize(new java.awt.Dimension(700, 600));
        backgroundPictureLabel.setMinimumSize(new java.awt.Dimension(700, 600));
        backgroundPictureLabel.setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backgroundPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(backgroundPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void faceToFaceDignoseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceToFaceDignoseButtonActionPerformed
        // TODO add your handling code here:
        Enumeration<AbstractButton> button;
        button=doctorJFrameButtonGroup.getElements();
        AbstractButton buttonChoose; //buttonChoose = jButton1 is true
        for(int i=0;i<doctorJFrameButtonGroup.getButtonCount();i++)
        {
            buttonChoose=button.nextElement();
            //            buttonChoose.setFocusPainted(false);
            //            buttonChoose.setMargin(new java.awt.Insets(0, 0, 0, 0));
            //            buttonChoose.setContentAreaFilled(false);
            //            buttonChoose.setBorderPainted(false);
            //            buttonChoose.setOpaque(true);
            buttonChoose.setBackground(new java.awt.Color(255, 255, 255));
            buttonChoose.setForeground(Color.black);

        }
        //        faceToFaceDignoseButton.setFocusPainted(true);
        //        faceToFaceDignoseButton.setMargin(new java.awt.Insets(1, 1, 1, 1));
        //        faceToFaceDignoseButton.setContentAreaFilled(true);
        //        faceToFaceDignoseButton.setBorderPainted(true);
        //        faceToFaceDignoseButton.setOpaque(true);
        faceToFaceDignoseButton.setBackground(new java.awt.Color(0, 0, 0));
        faceToFaceDignoseButton.setForeground(Color.white);
        DoctorFaceToFaceDiagnoseJPanel doctorFaceToFaceDiagnoseJPanel = new DoctorFaceToFaceDiagnoseJPanel(doctor);
        jSplitPane1.setRightComponent(doctorFaceToFaceDiagnoseJPanel);
    }//GEN-LAST:event_faceToFaceDignoseButtonActionPerformed

    private void loginOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginOutButtonActionPerformed
        // TODO add your handling code here:
        Enumeration<AbstractButton> button;
        button=doctorJFrameButtonGroup.getElements();
        AbstractButton buttonChoose; //buttonChoose = jButton1 is true
        for(int i=0;i<doctorJFrameButtonGroup.getButtonCount();i++)
        {
            buttonChoose=button.nextElement();
            buttonChoose.setBackground(new java.awt.Color(255, 255, 255));
            buttonChoose.setForeground(Color.black);

        }
        loginOutButton.setBackground(new java.awt.Color(0, 0, 0));
        loginOutButton.setForeground(Color.white);
        int value = JOptionPane.showConfirmDialog(rootPane, "Are you want to log out?");
        if (value == JOptionPane.YES_OPTION) {
            dispose();
            new TestMainJFrame().setVisible(true);
        }
    }//GEN-LAST:event_loginOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AccountantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AccountantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AccountantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AccountantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AccountantJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundPictureLabel;
    private javax.swing.ButtonGroup doctorJFrameButtonGroup;
    private javax.swing.JButton faceToFaceDignoseButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginOutButton;
    private javax.swing.JLabel nameMainLabel;
    // End of variables declaration//GEN-END:variables
}
