/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Club.Finance.Accountant;

//import UserInterface.Club.Finance.Accountant.*;
//import UserInterface.League.Match.Manager.*;
//import UserInterface.Club.Health.Doctor.*;
import TheClub.Finance.Accountant.Accountant;
import TheSystem.Common.Person.Person;
//import TheClub.Health.Doctor.Doctor;
import TheClub.Team.Team;
//import java.awt.Graphics;
import java.awt.Color;
import java.awt.Image;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;


/**
 *
 * @author Jiafeng
 */
public class AccountantJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountantJFrame
     */
    Accountant accountant;
    
    public AccountantJFrame(Person personTemp) {
        initComponents();
        Team team = new Team(personTemp); //初始化Team对象 里面含有全部的医生 Initialize the Team object containing all the Doctors
        
        int length = team.getDoctorCatalog().getDoctorCata().size();//计算catalog中有多少个医生 Calculate how many Doctors are in the catalog
        for(int i =0; i<length ; i++){
            Accountant accountantTemp = team.getAccountantCatalog().getAccountantCata().get(i);
            if(accountantTemp.getUsername().equals(personTemp.getUsername())){
                this.accountant=accountantTemp; 
                //找到在catalog中被初始化的那个accountant 和自己用户名一致的，将其对象指针传递过来
                //Find the accountant that was initialized in catalog that matches your username and pass it the object pointer
            }
        }

        Enumeration<AbstractButton> button;
        button=managerJFrameButtonGroup.getElements();
        AbstractButton buttonChoose; //buttonChoose = jButton1 is true
        for(int i=0;i<managerJFrameButtonGroup.getButtonCount();i++)
        {
              buttonChoose=button.nextElement();
              buttonChoose.setBackground(new java.awt.Color(255, 255, 255));
              buttonChoose.setForeground(Color.black);
            
        }   
    }
    
    //构造器 用于初始化 Constructor Used to initialize
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managerJFrameButtonGroup = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        allocateSalaryButton = new javax.swing.JButton();
        loginOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameMainLabel = new javax.swing.JLabel();
        nameMainLabel = new javax.swing.JLabel();
        viewSalaryStatisticsButton = new javax.swing.JButton();
        userNameMainLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backgroundPictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(800, 600));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(61, 174, 72));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 600));

        allocateSalaryButton.setText("<html>Allocate<br/>&#8202 Salary</html>");
        managerJFrameButtonGroup.add(allocateSalaryButton);
        allocateSalaryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        allocateSalaryButton.setMaximumSize(new java.awt.Dimension(90, 23));
        allocateSalaryButton.setMinimumSize(new java.awt.Dimension(90, 23));
        allocateSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocateSalaryButtonActionPerformed(evt);
            }
        });

        loginOutButton.setText("<html>Login Out</html>");
        managerJFrameButtonGroup.add(loginOutButton);
        loginOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginOutButton.setMaximumSize(new java.awt.Dimension(100, 23));
        loginOutButton.setMinimumSize(new java.awt.Dimension(72, 23));
        loginOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginOutButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UserName:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        userNameMainLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        userNameMainLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameMainLabel.setText("------------------");
        userNameMainLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameMainLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nameMainLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameMainLabel.setText("------------------");
        nameMainLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        viewSalaryStatisticsButton.setText("<html>View salary<br/>&#8202 statistics</html>");
        viewSalaryStatisticsButton.setActionCommand("<html>Diagnose<br/> Records</html>");
        managerJFrameButtonGroup.add(viewSalaryStatisticsButton);
        viewSalaryStatisticsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewSalaryStatisticsButton.setMaximumSize(new java.awt.Dimension(90, 23));
        viewSalaryStatisticsButton.setMinimumSize(new java.awt.Dimension(90, 23));
        viewSalaryStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalaryStatisticsButtonActionPerformed(evt);
            }
        });

        userNameMainLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        userNameMainLabel1.setForeground(new java.awt.Color(255, 255, 255));
        userNameMainLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameMainLabel1.setText("------------------");
        userNameMainLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewSalaryStatisticsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allocateSalaryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNameMainLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(nameMainLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNameMainLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(userNameMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameMainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(allocateSalaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(viewSalaryStatisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 139, 69));
        jPanel2.setMaximumSize(new java.awt.Dimension(700, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 600));

        backgroundPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TheSystem/Common/SelfDesignIcon/700_600_selfDesigned_ClubAccountant .png"))); // NOI18N
        backgroundPictureLabel.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backgroundPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(backgroundPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSalaryStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalaryStatisticsButtonActionPerformed
        // TODO add your handling code here:
        Enumeration<AbstractButton> button;
        button=managerJFrameButtonGroup.getElements();
        AbstractButton buttonChoose; //buttonChoose = jButton1 is true
        for(int i=0;i<managerJFrameButtonGroup.getButtonCount();i++)
        {
            buttonChoose=button.nextElement();
            buttonChoose.setBackground(new java.awt.Color(255, 255, 255));
            buttonChoose.setForeground(Color.black);

        }
        viewSalaryStatisticsButton.setBackground(new java.awt.Color(0, 0, 0));
        viewSalaryStatisticsButton.setForeground(Color.white);
        AccountantSallaryStatisticJPanel accountantSallaryStatisticJPanel = new AccountantSallaryStatisticJPanel(this.accountant);
        jSplitPane1.setRightComponent(accountantSallaryStatisticJPanel);     

        
    }//GEN-LAST:event_viewSalaryStatisticsButtonActionPerformed

    private void loginOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginOutButtonActionPerformed
        // TODO add your handling code here:
        Enumeration<AbstractButton> button;
        button=managerJFrameButtonGroup.getElements();
        AbstractButton buttonChoose; //buttonChoose = jButton1 is true
        for(int i=0;i<managerJFrameButtonGroup.getButtonCount();i++)
        {
            buttonChoose=button.nextElement();
            buttonChoose.setBackground(new java.awt.Color(255, 255, 255));
            buttonChoose.setForeground(Color.black);

        }
        loginOutButton.setBackground(new java.awt.Color(0, 0, 0));
        loginOutButton.setForeground(Color.white);
    }//GEN-LAST:event_loginOutButtonActionPerformed

    private void allocateSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocateSalaryButtonActionPerformed
        // TODO add your handling code here:
        Enumeration<AbstractButton> button;
        button=managerJFrameButtonGroup.getElements();
        AbstractButton buttonChoose; //buttonChoose = jButton1 is true
        for(int i=0;i<managerJFrameButtonGroup.getButtonCount();i++)
        {
            buttonChoose=button.nextElement();
            buttonChoose.setBackground(new java.awt.Color(255, 255, 255));
            buttonChoose.setForeground(Color.black);

        }
        allocateSalaryButton.setBackground(new java.awt.Color(0, 0, 0));
        allocateSalaryButton.setForeground(Color.white);
        
        AccountantAllocateSallaryJPanel accountantAllocateSallaryJPanel = new AccountantAllocateSallaryJPanel(this.accountant);
        jSplitPane1.setRightComponent(accountantAllocateSallaryJPanel);     
        
    }//GEN-LAST:event_allocateSalaryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AccountantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AccountantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AccountantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AccountantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AccountantJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allocateSalaryButton;
    private javax.swing.JLabel backgroundPictureLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginOutButton;
    private javax.swing.ButtonGroup managerJFrameButtonGroup;
    private javax.swing.JLabel nameMainLabel;
    private javax.swing.JLabel userNameMainLabel;
    private javax.swing.JLabel userNameMainLabel1;
    private javax.swing.JButton viewSalaryStatisticsButton;
    // End of variables declaration//GEN-END:variables
}
