/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Club.Team.Coach;

import TheSystem.Common.Person.Person;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Andrew Chou
 */
public class CoachFormationJPanel extends javax.swing.JPanel {
    Person person;
    /**
     * Creates new form CoachFormationJPanel
     */
    public CoachFormationJPanel(Person person_Pass) {
        initComponents();
        this.person = person_Pass;
        InitializeMatchInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UpcomingMatchLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FormationComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        FormationMainjPanel = new javax.swing.JPanel();
        FourThreeThreejPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FourFourTwojPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        FiveThreeTwojPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ThreeFiveTwojPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        FourTwoFourjPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        FourFiveOnejPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("Upcoming match:");

        UpcomingMatchLabel.setText("----------");

        jLabel3.setText("Date:");

        DateLabel.setText("----------");

        jLabel2.setText("Formation:");

        FormationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4-3-3", "4-4-2", "5-3-2", "3-5-2", "4-2-4", "4-5-1" }));
        FormationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormationComboBoxActionPerformed(evt);
            }
        });

        FormationMainjPanel.setLayout(new java.awt.CardLayout());

        jLabel4.setText("4-3-3");

        javax.swing.GroupLayout FourThreeThreejPanelLayout = new javax.swing.GroupLayout(FourThreeThreejPanel);
        FourThreeThreejPanel.setLayout(FourThreeThreejPanelLayout);
        FourThreeThreejPanelLayout.setHorizontalGroup(
            FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        FourThreeThreejPanelLayout.setVerticalGroup(
            FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FourThreeThreejPanel, "FourThreeThree");

        jLabel5.setText("4-4-2");

        javax.swing.GroupLayout FourFourTwojPanelLayout = new javax.swing.GroupLayout(FourFourTwojPanel);
        FourFourTwojPanel.setLayout(FourFourTwojPanelLayout);
        FourFourTwojPanelLayout.setHorizontalGroup(
            FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourFourTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        FourFourTwojPanelLayout.setVerticalGroup(
            FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourFourTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FourFourTwojPanel, "FourFourTwo");

        jLabel6.setText("5-3-2");

        javax.swing.GroupLayout FiveThreeTwojPanelLayout = new javax.swing.GroupLayout(FiveThreeTwojPanel);
        FiveThreeTwojPanel.setLayout(FiveThreeTwojPanelLayout);
        FiveThreeTwojPanelLayout.setHorizontalGroup(
            FiveThreeTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FiveThreeTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        FiveThreeTwojPanelLayout.setVerticalGroup(
            FiveThreeTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FiveThreeTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FiveThreeTwojPanel, "FiveThreeTwo");

        jLabel7.setText("3-5-2");

        javax.swing.GroupLayout ThreeFiveTwojPanelLayout = new javax.swing.GroupLayout(ThreeFiveTwojPanel);
        ThreeFiveTwojPanel.setLayout(ThreeFiveTwojPanelLayout);
        ThreeFiveTwojPanelLayout.setHorizontalGroup(
            ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        ThreeFiveTwojPanelLayout.setVerticalGroup(
            ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(ThreeFiveTwojPanel, "ThreeFiveTwo");

        jLabel8.setText("4-2-4");

        javax.swing.GroupLayout FourTwoFourjPanelLayout = new javax.swing.GroupLayout(FourTwoFourjPanel);
        FourTwoFourjPanel.setLayout(FourTwoFourjPanelLayout);
        FourTwoFourjPanelLayout.setHorizontalGroup(
            FourTwoFourjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourTwoFourjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        FourTwoFourjPanelLayout.setVerticalGroup(
            FourTwoFourjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourTwoFourjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FourTwoFourjPanel, "FourTwoFour");

        jLabel9.setText("4-5-1");

        javax.swing.GroupLayout FourFiveOnejPanelLayout = new javax.swing.GroupLayout(FourFiveOnejPanel);
        FourFiveOnejPanel.setLayout(FourFiveOnejPanelLayout);
        FourFiveOnejPanelLayout.setHorizontalGroup(
            FourFiveOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourFiveOnejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        FourFiveOnejPanelLayout.setVerticalGroup(
            FourFiveOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourFiveOnejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FourFiveOnejPanel, "FourFiveOne");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormationMainjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpcomingMatchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FormationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UpcomingMatchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FormationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormationMainjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FormationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormationComboBoxActionPerformed
        // TODO add your handling code here:
        if(String.valueOf(this.FormationComboBox.getSelectedItem()).equals("4-3-3")){
            CardLayout card = (CardLayout)FormationMainjPanel.getLayout();
            card.show(FormationMainjPanel, "FourThreeThree");
        }else if(String.valueOf(this.FormationComboBox.getSelectedItem()).equals("4-4-2")){
            CardLayout card = (CardLayout)FormationMainjPanel.getLayout();
            card.show(FormationMainjPanel, "FourFourTwo");
        }else if(String.valueOf(this.FormationComboBox.getSelectedItem()).equals("5-3-2")){
            CardLayout card = (CardLayout)FormationMainjPanel.getLayout();
            card.show(FormationMainjPanel, "FiveThreeTwo");
        }else if(String.valueOf(this.FormationComboBox.getSelectedItem()).equals("3-5-2")){
            CardLayout card = (CardLayout)FormationMainjPanel.getLayout();
            card.show(FormationMainjPanel, "ThreeFiveTwo");
        }else if(String.valueOf(this.FormationComboBox.getSelectedItem()).equals("4-2-4")){
            CardLayout card = (CardLayout)FormationMainjPanel.getLayout();
            card.show(FormationMainjPanel, "FourTwoFour");
        }else if(String.valueOf(this.FormationComboBox.getSelectedItem()).equals("4-5-1")){
            CardLayout card = (CardLayout)FormationMainjPanel.getLayout();
            card.show(FormationMainjPanel, "FourFiveOne");
        }
    }//GEN-LAST:event_FormationComboBoxActionPerformed

    public final void InitializeMatchInfo(){
        String upcoming_Home = "";
        String upcoming_Away = "";
        String upcoming_Date = "";
        String team_Name;
        team_Name = person.getClub();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/premierleague?zeroDateTimeBehavior=CONVERT_TO_NULL";
            String username = "root";
            String password = "150823";
            Connection connection = DriverManager.getConnection(url, username, password);
            Statement statement = connection.createStatement();
            String sql = "SELECT * FROM match_info WHERE home=\'" + team_Name + "\' "
                    + "OR away=\'" + team_Name + "\' ORDER BY date ASC";
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                upcoming_Home = String.valueOf(resultSet.getObject("home"));
                upcoming_Away = String.valueOf(resultSet.getObject("away"));
                upcoming_Date = String.valueOf(resultSet.getObject("date"));
                break;
            }
            this.UpcomingMatchLabel.setText(upcoming_Home + " VS " + upcoming_Away);
            this.DateLabel.setText(upcoming_Date);
            resultSet.close();
            statement.close();
            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLabel;
    private javax.swing.JPanel FiveThreeTwojPanel;
    private javax.swing.JComboBox<String> FormationComboBox;
    private javax.swing.JPanel FormationMainjPanel;
    private javax.swing.JPanel FourFiveOnejPanel;
    private javax.swing.JPanel FourFourTwojPanel;
    private javax.swing.JPanel FourThreeThreejPanel;
    private javax.swing.JPanel FourTwoFourjPanel;
    private javax.swing.JPanel ThreeFiveTwojPanel;
    private javax.swing.JLabel UpcomingMatchLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
