/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Club.Team.Coach;

import TheSystem.Common.Person.Person;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Andrew Chou
 */
public class CoachFormationJPanel extends javax.swing.JPanel {
    Person person;
    String upcoming_Home;
    String upcoming_Away;
    String upcoming_Date;
    String formation;
    ArrayList<String> playerList = new ArrayList<>();
    // List used to submit first line-up 
    ArrayList<String> firstPlayerList = new ArrayList<>();
    // list used to sumit alternate
    ArrayList<String> substitutePlayerList = new ArrayList<>();
    /**
     * Creates new form CoachFormationJPanel
     */
    public CoachFormationJPanel(Person person_Pass) {
        initComponents();
        this.person = person_Pass;
        InitializeMatchInfo();
        this.PlayerConfirmButton.setEnabled(false);
        this.NamelistComboBox.setEnabled(false);
        this.SubstitutionComboBox.setEnabled(false);
        this.AddButton.setEnabled(false);
        this.DeleteButton.setEnabled(false);
        this.SubmitButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UpcomingMatchLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FormationComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        FormationMainjPanel = new javax.swing.JPanel();
        FourThreeThreejPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ALWComboBox = new javax.swing.JComboBox<>();
        ARWComboBox = new javax.swing.JComboBox<>();
        ASTComboBox = new javax.swing.JComboBox<>();
        ARMComboBox = new javax.swing.JComboBox<>();
        ALMComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ACMComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ALWBComboBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ARWBComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ARBComboBox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        ALBComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        AGKComboBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        FourFourTwojPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BLWMComboBox = new javax.swing.JComboBox<>();
        BRWMComboBox = new javax.swing.JComboBox<>();
        BLMComboBox = new javax.swing.JComboBox<>();
        BRMComboBox = new javax.swing.JComboBox<>();
        BLSComboBox = new javax.swing.JComboBox<>();
        BRSComboBox = new javax.swing.JComboBox<>();
        BLWBComboBox = new javax.swing.JComboBox<>();
        BLBComboBox = new javax.swing.JComboBox<>();
        BRBComboBox = new javax.swing.JComboBox<>();
        BRWBComboBox = new javax.swing.JComboBox<>();
        BGKComboBox = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        FiveThreeTwojPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ThreeFiveTwojPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DLWMComboBox = new javax.swing.JComboBox<>();
        DRWMComboBox = new javax.swing.JComboBox<>();
        DRMComboBox = new javax.swing.JComboBox<>();
        DLMComboBox = new javax.swing.JComboBox<>();
        DCMComboBox = new javax.swing.JComboBox<>();
        DCBComboBox = new javax.swing.JComboBox<>();
        DRBComboBox = new javax.swing.JComboBox<>();
        DLBComboBox = new javax.swing.JComboBox<>();
        DRSComboBox = new javax.swing.JComboBox<>();
        DLSComboBox = new javax.swing.JComboBox<>();
        DGKComboBox = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        FourTwoFourjPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        FourFiveOnejPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        FormationConfirmButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        PlayerConfirmButton = new javax.swing.JButton();
        NamelistComboBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        SubstitutionComboBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 139, 69));

        jLabel1.setText("Upcoming match:");

        UpcomingMatchLabel.setText("----------");

        jLabel3.setText("Date:");

        DateLabel.setText("----------");

        jLabel2.setText("Formation:");

        FormationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4-3-3", "4-4-2", "5-3-2", "3-5-2", "4-2-4", "4-5-1" }));
        FormationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormationComboBoxActionPerformed(evt);
            }
        });

        FormationMainjPanel.setPreferredSize(new java.awt.Dimension(448, 275));
        FormationMainjPanel.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel4.setText("4-3-3");

        ALWComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        ARWComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        ASTComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        ARMComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        ALMComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        jLabel10.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel10.setText("ST");

        jLabel11.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel11.setText("LW");

        jLabel12.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel12.setText("RW");

        jLabel13.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel13.setText("LM");

        ACMComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        jLabel14.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel14.setText("CM");

        jLabel15.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel15.setText("RM");

        ALWBComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        jLabel16.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel16.setText("LWB");

        ARWBComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        jLabel18.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel18.setText("RWB");

        ARBComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        jLabel19.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel19.setText("RB");

        ALBComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        jLabel20.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel20.setText("LB");

        AGKComboBox.setMaximumSize(new java.awt.Dimension(72, 23));

        jLabel17.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel17.setText("GK");

        javax.swing.GroupLayout FourThreeThreejPanelLayout = new javax.swing.GroupLayout(FourThreeThreejPanel);
        FourThreeThreejPanel.setLayout(FourThreeThreejPanelLayout);
        FourThreeThreejPanelLayout.setHorizontalGroup(
            FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                        .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(ALWComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(ARWComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FourThreeThreejPanelLayout.createSequentialGroup()
                        .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ALMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ALWBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(ALBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(ASTComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(ACMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(110, 110, 110)
                                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(ARMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17)
                            .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                                .addComponent(AGKComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                                        .addComponent(ARBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(ARWBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );
        FourThreeThreejPanelLayout.setVerticalGroup(
            FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ASTComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ARWComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ALWComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ALMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FourThreeThreejPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FourThreeThreejPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ARMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FourThreeThreejPanelLayout.createSequentialGroup()
                                .addComponent(ACMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel14)
                                .addGap(2, 2, 2)))))
                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel18))
                    .addGroup(FourThreeThreejPanelLayout.createSequentialGroup()
                        .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ALWBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ARWBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ALBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ARBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FourThreeThreejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(AGKComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FourThreeThreejPanel, "FourThreeThree");

        jLabel5.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel5.setText("4-4-2");

        jLabel23.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel23.setText("LS");

        jLabel24.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel24.setText("RS");

        jLabel25.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel25.setText("LWM");

        jLabel26.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel26.setText("LM");

        jLabel27.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel27.setText("RM");

        jLabel28.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel28.setText("RWM");

        jLabel29.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel29.setText("LWB");

        jLabel30.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel30.setText("LB");

        jLabel31.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel31.setText("RB");

        jLabel32.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel32.setText("RWB");

        jLabel33.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel33.setText("GK");

        javax.swing.GroupLayout FourFourTwojPanelLayout = new javax.swing.GroupLayout(FourFourTwojPanel);
        FourFourTwojPanel.setLayout(FourFourTwojPanelLayout);
        FourFourTwojPanelLayout.setHorizontalGroup(
            FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourFourTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FourFourTwojPanelLayout.createSequentialGroup()
                        .addComponent(BLWMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BLMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BLSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel25)
                    .addGroup(FourFourTwojPanelLayout.createSequentialGroup()
                        .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BLWBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30)
                            .addComponent(BLBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BRSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(FourFourTwojPanelLayout.createSequentialGroup()
                            .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BRMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27))
                            .addGap(18, 18, 18)
                            .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28)
                                .addComponent(BRWMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FourFourTwojPanelLayout.createSequentialGroup()
                            .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BRBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BRWBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel24))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FourFourTwojPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(BGKComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(186, 186, 186))
        );
        FourFourTwojPanelLayout.setVerticalGroup(
            FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourFourTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BLSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BRSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FourFourTwojPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BLWMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BLMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BRMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BRWMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27))
                            .addComponent(jLabel28))
                        .addGap(25, 25, 25)
                        .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BLWBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BLBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BRBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BRWBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addGroup(FourFourTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(BGKComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FourFourTwojPanel, "FourFourTwo");

        jLabel6.setText("5-3-2");

        javax.swing.GroupLayout FiveThreeTwojPanelLayout = new javax.swing.GroupLayout(FiveThreeTwojPanel);
        FiveThreeTwojPanel.setLayout(FiveThreeTwojPanelLayout);
        FiveThreeTwojPanelLayout.setHorizontalGroup(
            FiveThreeTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FiveThreeTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        FiveThreeTwojPanelLayout.setVerticalGroup(
            FiveThreeTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FiveThreeTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FiveThreeTwojPanel, "FiveThreeTwo");

        jLabel7.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel7.setText("3-5-2");

        jLabel34.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel34.setText("LS");

        jLabel35.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel35.setText("RS");

        jLabel36.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel36.setText("LWM");

        jLabel37.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel37.setText("LM");

        jLabel38.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel38.setText("CM");

        jLabel39.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel39.setText("RM");

        jLabel40.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel40.setText("RWM");

        jLabel41.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel41.setText("LB");

        jLabel42.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel42.setText("CB");

        jLabel43.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel43.setText("RB");

        jLabel44.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel44.setText("GK");

        javax.swing.GroupLayout ThreeFiveTwojPanelLayout = new javax.swing.GroupLayout(ThreeFiveTwojPanel);
        ThreeFiveTwojPanel.setLayout(ThreeFiveTwojPanelLayout);
        ThreeFiveTwojPanelLayout.setHorizontalGroup(
            ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThreeFiveTwojPanelLayout.createSequentialGroup()
                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DLSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DLBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel41))
                        .addGap(18, 18, 18))
                    .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DLWMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(DLMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                                .addComponent(DCMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DRMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                                .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DGKComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                                        .addComponent(DCBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DRSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DRBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel43)))
                                    .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(85, 85, 85)
                                        .addComponent(jLabel39)))
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DRWMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)))
                    .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel42))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ThreeFiveTwojPanelLayout.setVerticalGroup(
            ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DRSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DLSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(28, 28, 28)
                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DLWMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DRWMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DRMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DLMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DCMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(jLabel37)
                        .addComponent(jLabel38))
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addGap(14, 14, 14)
                .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DCBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DRBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DLBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThreeFiveTwojPanelLayout.createSequentialGroup()
                        .addGroup(ThreeFiveTwojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel43))
                        .addGap(7, 7, 7)
                        .addComponent(DGKComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(ThreeFiveTwojPanel, "ThreeFiveTwo");

        jLabel8.setText("4-2-4");

        javax.swing.GroupLayout FourTwoFourjPanelLayout = new javax.swing.GroupLayout(FourTwoFourjPanel);
        FourTwoFourjPanel.setLayout(FourTwoFourjPanelLayout);
        FourTwoFourjPanelLayout.setHorizontalGroup(
            FourTwoFourjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourTwoFourjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        FourTwoFourjPanelLayout.setVerticalGroup(
            FourTwoFourjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourTwoFourjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FourTwoFourjPanel, "FourTwoFour");

        jLabel9.setText("4-5-1");

        javax.swing.GroupLayout FourFiveOnejPanelLayout = new javax.swing.GroupLayout(FourFiveOnejPanel);
        FourFiveOnejPanel.setLayout(FourFiveOnejPanelLayout);
        FourFiveOnejPanelLayout.setHorizontalGroup(
            FourFiveOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourFiveOnejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        FourFiveOnejPanelLayout.setVerticalGroup(
            FourFiveOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourFiveOnejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        FormationMainjPanel.add(FourFiveOnejPanel, "FourFiveOne");

        FormationConfirmButton.setFont(new java.awt.Font("Consolas", 2, 12)); // NOI18N
        FormationConfirmButton.setText("Confirm");
        FormationConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormationConfirmButtonActionPerformed(evt);
            }
        });

        PlayerConfirmButton.setFont(new java.awt.Font("Consolas", 2, 12)); // NOI18N
        PlayerConfirmButton.setText("Confirm");
        PlayerConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerConfirmButtonActionPerformed(evt);
            }
        });

        NamelistComboBox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                NamelistComboBoxMouseDragged(evt);
            }
        });
        NamelistComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NamelistComboBoxMouseClicked(evt);
            }
        });
        NamelistComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamelistComboBoxActionPerformed(evt);
            }
        });

        jLabel21.setText("NameList:");

        jLabel22.setText("Substitution:");

        AddButton.setFont(new java.awt.Font("Consolas", 2, 12)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Consolas", 2, 12)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Consolas", 2, 12)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormationMainjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpcomingMatchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FormationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FormationConfirmButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SubmitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SubstitutionComboBox, 0, 100, Short.MAX_VALUE)
                                    .addComponent(NamelistComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(184, 184, 184))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(43, 43, 43)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PlayerConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UpcomingMatchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FormationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormationConfirmButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormationMainjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerConfirmButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(NamelistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(SubstitutionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(SubmitButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FormationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormationComboBoxActionPerformed

    private void FormationConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormationConfirmButtonActionPerformed
        // TODO add your handling code here:
        formation = (String) this.FormationComboBox.getSelectedItem();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/premierleague?zeroDateTimeBehavior=CONVERT_TO_NULL";
            String username = "root";
            String password = "abcd1234!";
            Connection connection = DriverManager.getConnection(url, username, password);
            Statement statement = connection.createStatement();
            String sql = "SELECT * FROM system_user_info WHERE club=\'" + this.person.getClub() + "\' AND role_type=\'2\'";
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                playerList.add(String.valueOf(resultSet.getObject("username")));
            }
            resultSet.close();
            statement.close();
            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
        }
        switch (String.valueOf(this.FormationComboBox.getSelectedItem())) {
            case "4-3-3" :
                for (String name : playerList) {
                    this.ALWComboBox.addItem(name);
                    this.ASTComboBox.addItem(name);
                    this.ARWComboBox.addItem(name);
                    this.ALMComboBox.addItem(name);
                    this.ACMComboBox.addItem(name);
                    this.ARMComboBox.addItem(name);
                    this.ALWBComboBox.addItem(name);
                    this.ALBComboBox.addItem(name);
                    this.ARBComboBox.addItem(name);
                    this.ARWBComboBox.addItem(name);
                    this.AGKComboBox.addItem(name);
                }
                this.ALWComboBox.setSelectedIndex(-1);
                this.ASTComboBox.setSelectedIndex(-1);
                this.ARWComboBox.setSelectedIndex(-1);
                this.ALMComboBox.setSelectedIndex(-1);
                this.ACMComboBox.setSelectedIndex(-1);
                this.ARMComboBox.setSelectedIndex(-1);
                this.ALWBComboBox.setSelectedIndex(-1);
                this.ALBComboBox.setSelectedIndex(-1);
                this.ARBComboBox.setSelectedIndex(-1);
                this.ARWBComboBox.setSelectedIndex(-1);
                this.AGKComboBox.setSelectedIndex(-1);
                CardLayout card = (CardLayout) FormationMainjPanel.getLayout();
                card.show(FormationMainjPanel, "FourThreeThree");
                
            case "4-4-2" :
                for (String name : playerList) {
                    this.BLSComboBox.addItem(name);
                    this.BRSComboBox.addItem(name);
                    this.BLWMComboBox.addItem(name);
                    this.BLMComboBox.addItem(name);
                    this.BRMComboBox.addItem(name);
                    this.BRWMComboBox.addItem(name);
                    this.BLWBComboBox.addItem(name);
                    this.BLBComboBox.addItem(name);
                    this.BRBComboBox.addItem(name);
                    this.BRWBComboBox.addItem(name);
                    this.BGKComboBox.addItem(name);
                }
                this.BLSComboBox.setSelectedIndex(-1);
                this.BRSComboBox.setSelectedIndex(-1);
                this.BLWMComboBox.setSelectedIndex(-1);
                this.BLMComboBox.setSelectedIndex(-1);
                this.BRMComboBox.setSelectedIndex(-1);
                this.BRWMComboBox.setSelectedIndex(-1);
                this.BLWBComboBox.setSelectedIndex(-1);
                this.BLBComboBox.setSelectedIndex(-1);
                this.BRBComboBox.setSelectedIndex(-1);
                this.BRWBComboBox.setSelectedIndex(-1);
                this.BGKComboBox.setSelectedIndex(-1);
                CardLayout bcard = (CardLayout) FormationMainjPanel.getLayout();
                bcard.show(FormationMainjPanel, "FourFourTwo");
            
            case "5-3-2" :                
                    CardLayout ccard = (CardLayout)FormationMainjPanel.getLayout();
                    ccard.show(FormationMainjPanel, "FiveThreeTwo");
                
            case "3-5-2" :
                for (String name : playerList) {
                    this.DLSComboBox.addItem(name);
                    this.DRSComboBox.addItem(name);
                    this.DLWMComboBox.addItem(name);
                    this.DLMComboBox.addItem(name);
                    this.DCMComboBox.addItem(name);
                    this.DRMComboBox.addItem(name);
                    this.DRWMComboBox.addItem(name);
                    this.DLBComboBox.addItem(name);
                    this.DCBComboBox.addItem(name);
                    this.DRBComboBox.addItem(name);
                    this.DGKComboBox.addItem(name);
                }
                this.DLSComboBox.setSelectedIndex(-1);
                this.DRSComboBox.setSelectedIndex(-1);
                this.DLWMComboBox.setSelectedIndex(-1);
                this.DLMComboBox.setSelectedIndex(-1);
                this.DCMComboBox.setSelectedIndex(-1);
                this.DRMComboBox.setSelectedIndex(-1);
                this.DRWMComboBox.setSelectedIndex(-1);
                this.DLBComboBox.setSelectedIndex(-1);
                this.DCBComboBox.setSelectedIndex(-1);
                this.DRBComboBox.setSelectedIndex(-1);
                this.DGKComboBox.setSelectedIndex(-1);
                CardLayout dcard = (CardLayout) FormationMainjPanel.getLayout();
                dcard.show(FormationMainjPanel, "ThreeFiveTwo");
            
            case "4-2-4" :                
                    CardLayout ecard = (CardLayout)FormationMainjPanel.getLayout();
                    ecard.show(FormationMainjPanel, "FourTwoFour");
                
            case "4-5-1" :            
                    CardLayout fcard = (CardLayout)FormationMainjPanel.getLayout();
                    fcard.show(FormationMainjPanel, "FourFiveOne");
                
            default : {
            }
        }
        this.FormationComboBox.setEnabled(false);
        this.FormationConfirmButton.setEnabled(false);
        this.PlayerConfirmButton.setEnabled(true);
    }//GEN-LAST:event_FormationConfirmButtonActionPerformed

    private void PlayerConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerConfirmButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<String> temp_PlayerList = new ArrayList<>();
        ArrayList<String> compare_PlayerList = new ArrayList<>();
        for(String str:playerList){
            temp_PlayerList.add(str);
        }
        if(String.valueOf(this.FormationComboBox.getSelectedItem()).equals("4-3-3")){
            compare_PlayerList.add(String.valueOf(this.ALWComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ASTComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ARWComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ALMComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ACMComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ARMComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ALWBComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ALBComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ARBComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.ARWBComboBox.getSelectedItem()));
            compare_PlayerList.add(String.valueOf(this.AGKComboBox.getSelectedItem())); 
            if(judgeDuplicate(compare_PlayerList)){
                JOptionPane.showMessageDialog(ARBComboBox, "Duplicate Selection or Empty Selection Exists!", "Warning", JOptionPane.DEFAULT_OPTION);
            }else{
                firstPlayerList.add(String.valueOf(this.ALWComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ASTComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ARWComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ALMComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ACMComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ARMComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ALWBComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ALBComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ARBComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.ARWBComboBox.getSelectedItem()));
                firstPlayerList.add(String.valueOf(this.AGKComboBox.getSelectedItem())); 
            
                temp_PlayerList.remove(String.valueOf(this.ALWComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ASTComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ARWComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ALMComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ACMComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ARMComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ALWBComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ALBComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ARBComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.ARWBComboBox.getSelectedItem()));
                temp_PlayerList.remove(String.valueOf(this.AGKComboBox.getSelectedItem()));
                
                this.NamelistComboBox.setEnabled(true);
                
                for (String str : temp_PlayerList) {
                    this.NamelistComboBox.addItem(str); 
                }   
                this.NamelistComboBox.setSelectedIndex(-1);
                this.PlayerConfirmButton.setEnabled(false);
                this.NamelistComboBox.setEnabled(true);
                this.SubstitutionComboBox.setEnabled(true);
                this.AddButton.setEnabled(true);
                this.DeleteButton.setEnabled(true);
                this.SubmitButton.setEnabled(true);
            }
        }else if(this.FormationComboBox.getSelectedItem().equals("4-4-2")){
            compare_PlayerList.add((String) this.BLSComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BRSComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BLWMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BLMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BRMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BRWMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BLWBComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BLBComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BRBComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BRWBComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.BGKComboBox.getSelectedItem());
            if(judgeDuplicate(compare_PlayerList)){
                JOptionPane.showMessageDialog(ARBComboBox, "Duplicate Selection or Empty Selection Exists!", "Warning", JOptionPane.DEFAULT_OPTION);
            } else {
                firstPlayerList.add((String) this.BLSComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BRSComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BLWMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BLMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BRMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BRWMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BLWBComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BLBComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BRBComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BRWBComboBox.getSelectedItem());
                firstPlayerList.add((String) this.BGKComboBox.getSelectedItem());
                
                temp_PlayerList.remove((String) this.BLSComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BRSComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BLWMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BLMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BRMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BRWMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BLWBComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BLBComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BRBComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BRWBComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.BGKComboBox.getSelectedItem());

                this.NamelistComboBox.setEnabled(true);
                
                for (String str : temp_PlayerList) {
                    this.NamelistComboBox.addItem(str); 
                }   
                this.NamelistComboBox.setSelectedIndex(-1);
                this.PlayerConfirmButton.setEnabled(false);
                this.NamelistComboBox.setEnabled(true);
                this.SubstitutionComboBox.setEnabled(true);
                this.AddButton.setEnabled(true);
                this.DeleteButton.setEnabled(true);
                this.SubmitButton.setEnabled(true);
            }
        }else if(this.FormationComboBox.getSelectedItem().equals("3-5-2")){
            compare_PlayerList.add((String) this.DLSComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DRSComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DLWMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DLMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DCMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DRMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DRWMComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DLBComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DCBComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DRBComboBox.getSelectedItem());
            compare_PlayerList.add((String) this.DGKComboBox.getSelectedItem());
            if(judgeDuplicate(compare_PlayerList)){
                JOptionPane.showMessageDialog(ARBComboBox, "Duplicate Selection or Empty Selection Exists!", "Warning", JOptionPane.DEFAULT_OPTION);
            } else {
                firstPlayerList.add((String) this.DLSComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DRSComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DLWMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DLMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DCMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DRMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DRWMComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DLBComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DCBComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DRBComboBox.getSelectedItem());
                firstPlayerList.add((String) this.DGKComboBox.getSelectedItem());
                
                temp_PlayerList.remove((String) this.DLSComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DRSComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DLWMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DLMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DCMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DRMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DRWMComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DLBComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DCBComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DRBComboBox.getSelectedItem());
                temp_PlayerList.remove((String) this.DGKComboBox.getSelectedItem());
                
                this.NamelistComboBox.setEnabled(true);
                for (String str : temp_PlayerList) {
                    this.NamelistComboBox.addItem(str); 
                }   
                this.NamelistComboBox.setSelectedIndex(-1);
                this.PlayerConfirmButton.setEnabled(false);
                this.NamelistComboBox.setEnabled(true);
                this.SubstitutionComboBox.setEnabled(true);
                this.AddButton.setEnabled(true);
                this.DeleteButton.setEnabled(true);
                this.SubmitButton.setEnabled(true);
            }
        }
        
    }//GEN-LAST:event_PlayerConfirmButtonActionPerformed

    private void NamelistComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamelistComboBoxActionPerformed
        // TODO add your handling code here:
//        if (String.valueOf(this.NamelistComboBox.getSelectedItem()).length()!=0) {
//            int n = JOptionPane.showConfirmDialog(ARBComboBox, "Are you sure want to add this player to the substitution?", "Confirmation", JOptionPane.YES_NO_OPTION);
//            System.out.println(n);
//        }
    }//GEN-LAST:event_NamelistComboBoxActionPerformed

    private void NamelistComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NamelistComboBoxMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_NamelistComboBoxMouseClicked

    private void NamelistComboBoxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NamelistComboBoxMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_NamelistComboBoxMouseDragged

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        if(this.NamelistComboBox.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(ARBComboBox, "Please select a Player first!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            int n = JOptionPane.showConfirmDialog(ARBComboBox, "Are you sure want to add this player to the substitution?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (n == 0) {
                this.SubstitutionComboBox.addItem((String) this.NamelistComboBox.getSelectedItem());
                this.NamelistComboBox.removeItemAt(this.NamelistComboBox.getSelectedIndex());
                this.NamelistComboBox.setSelectedIndex(-1);
                this.SubstitutionComboBox.setSelectedIndex(-1);
            }
        }
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        if (this.SubstitutionComboBox.getItemCount() == 0) {
            JOptionPane.showMessageDialog(ARBComboBox, "There's no one in the substitution list!", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i = 0; i < this.SubstitutionComboBox.getItemCount(); i++) {
                this.substitutePlayerList.add(this.SubstitutionComboBox.getItemAt(i));
            }
            String alternate = "";
            for (String str : substitutePlayerList) {
                alternate = alternate + str + ",";
            }
            String line_Up = "";
            for (String str : firstPlayerList) {
                line_Up = line_Up + str + ",";
            }
            boolean home_away;
            if (upcoming_Home.equals(this.person.getClub())) {
                home_away = true;
            } else {
                home_away = false;
            }
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/premierleague?zeroDateTimeBehavior=CONVERT_TO_NULL";
                String username = "root";
                String password = "abcd1234!";
                Connection connection = DriverManager.getConnection(url, username, password);
                Statement statement = connection.createStatement();
                String sql = null;
                if (home_away) {
                    sql = "UPDATE match_info SET home_formation=\'" + formation + "\', home_lineup=\'" + line_Up + "\', home_alternate=\'" + alternate + "\'"
                            + "WHERE home=\'" + upcoming_Home + "\' AND away=\'" + upcoming_Away + "\' AND date=\'" + upcoming_Date + "\'";
                } else {
                    sql = "UPDATE match_info SET away_formation=\'" + formation + "\', away_lineup=\'" + line_Up + "\', away_alternate=\'" + alternate + "\'"
                            + "WHERE home=\'" + upcoming_Home + "\' AND away=\'" + upcoming_Away + "\' AND date=\'" + upcoming_Date + "\'";
                }
                int result = statement.executeUpdate(sql);
                if (result == 1) {
                    JOptionPane.showMessageDialog(ARBComboBox, "Successful!", "Congratulations!", JOptionPane.INFORMATION_MESSAGE);
                    this.FormationComboBox.setEnabled(true);
                    this.FormationConfirmButton.setEnabled(true);
                    this.PlayerConfirmButton.setEnabled(false);
                    this.NamelistComboBox.setEnabled(false);
                    this.SubstitutionComboBox.setEnabled(false);
                    this.AddButton.setEnabled(false);
                    this.DeleteButton.setEnabled(false);
                    this.SubmitButton.setEnabled(false);
                }

                statement.close();
                connection.close();
            } catch (ClassNotFoundException | SQLException e) {
            }
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        if (this.SubstitutionComboBox.getItemCount() == 0) {
            JOptionPane.showMessageDialog(ARBComboBox, "There's no one in the substitution list!", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            if (this.SubstitutionComboBox.getSelectedIndex()==-1) {
                JOptionPane.showMessageDialog(ARBComboBox, "Please select a Player first!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                int n = JOptionPane.showConfirmDialog(ARBComboBox, "Are you sure want to delete this player from the substitution?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    this.NamelistComboBox.addItem((String) this.SubstitutionComboBox.getSelectedItem());
                    this.SubstitutionComboBox.removeItemAt(this.SubstitutionComboBox.getSelectedIndex());
                    this.NamelistComboBox.setSelectedIndex(-1);
                    this.SubstitutionComboBox.setSelectedIndex(-1);
                }
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    public final void InitializeMatchInfo(){
        
        String team_Name;
        team_Name = person.getClub();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/premierleague?zeroDateTimeBehavior=CONVERT_TO_NULL";
            String username = "root";
            String password = "abcd1234!";
            Connection connection = DriverManager.getConnection(url, username, password);
            Statement statement = connection.createStatement();
            String sql = "SELECT * FROM match_info WHERE home=\'" + team_Name + "\' "
                    + "OR away=\'" + team_Name + "\' ORDER BY date ASC";
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                upcoming_Home = String.valueOf(resultSet.getObject("home"));
                upcoming_Away = String.valueOf(resultSet.getObject("away"));
                upcoming_Date = String.valueOf(resultSet.getObject("date"));
                break;
            }
            this.UpcomingMatchLabel.setText(upcoming_Home + " VS " + upcoming_Away);
            this.DateLabel.setText(upcoming_Date);
            resultSet.close();
            statement.close();
            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
        }
    }
    public boolean judgeDuplicate(ArrayList<String> list) {
        HashSet<String> set = new HashSet<>(list);
        boolean result = !(set.size() == list.size());
        return result;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ACMComboBox;
    private javax.swing.JComboBox<String> AGKComboBox;
    private javax.swing.JComboBox<String> ALBComboBox;
    private javax.swing.JComboBox<String> ALMComboBox;
    private javax.swing.JComboBox<String> ALWBComboBox;
    private javax.swing.JComboBox<String> ALWComboBox;
    private javax.swing.JComboBox<String> ARBComboBox;
    private javax.swing.JComboBox<String> ARMComboBox;
    private javax.swing.JComboBox<String> ARWBComboBox;
    private javax.swing.JComboBox<String> ARWComboBox;
    private javax.swing.JComboBox<String> ASTComboBox;
    private javax.swing.JButton AddButton;
    private javax.swing.JComboBox<String> BGKComboBox;
    private javax.swing.JComboBox<String> BLBComboBox;
    private javax.swing.JComboBox<String> BLMComboBox;
    private javax.swing.JComboBox<String> BLSComboBox;
    private javax.swing.JComboBox<String> BLWBComboBox;
    private javax.swing.JComboBox<String> BLWMComboBox;
    private javax.swing.JComboBox<String> BRBComboBox;
    private javax.swing.JComboBox<String> BRMComboBox;
    private javax.swing.JComboBox<String> BRSComboBox;
    private javax.swing.JComboBox<String> BRWBComboBox;
    private javax.swing.JComboBox<String> BRWMComboBox;
    private javax.swing.JComboBox<String> DCBComboBox;
    private javax.swing.JComboBox<String> DCMComboBox;
    private javax.swing.JComboBox<String> DGKComboBox;
    private javax.swing.JComboBox<String> DLBComboBox;
    private javax.swing.JComboBox<String> DLMComboBox;
    private javax.swing.JComboBox<String> DLSComboBox;
    private javax.swing.JComboBox<String> DLWMComboBox;
    private javax.swing.JComboBox<String> DRBComboBox;
    private javax.swing.JComboBox<String> DRMComboBox;
    private javax.swing.JComboBox<String> DRSComboBox;
    private javax.swing.JComboBox<String> DRWMComboBox;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JPanel FiveThreeTwojPanel;
    private javax.swing.JComboBox<String> FormationComboBox;
    private javax.swing.JButton FormationConfirmButton;
    private javax.swing.JPanel FormationMainjPanel;
    private javax.swing.JPanel FourFiveOnejPanel;
    private javax.swing.JPanel FourFourTwojPanel;
    private javax.swing.JPanel FourThreeThreejPanel;
    private javax.swing.JPanel FourTwoFourjPanel;
    private javax.swing.JComboBox<String> NamelistComboBox;
    private javax.swing.JButton PlayerConfirmButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JComboBox<String> SubstitutionComboBox;
    private javax.swing.JPanel ThreeFiveTwojPanel;
    private javax.swing.JLabel UpcomingMatchLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
